spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3307/pupil_info
    username: root
    password: testtest
  jpa:
    show-sql: true
  flyway:
    schemas=pupil_info: