spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3307/pupil_info
    username: root
    password: testtest
  jpa:
    show-sql: true
  flyway:
    enabled: true
    schemas: pupil_info
    default-schema: pupil_info
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration